# Site Settings

paginate:            5
highlighter:         rouge


title: Kirill Bykov
description: Postdoctoral Machine Learning Researcher @ TUM
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
plugins:             [jekyll-paginate-v2, jekyll-sitemap, jekyll-feed]

gems:
  - jekyll-feed
  - jekyll-paginate

# Customise feed settings (uncommenting following two fields to customise feed title and description)
#title:		     "Kirill Bykov"
#description:	     "Postdoctoral Machine Learning Researcher"
#twitter:	    "https://twitter.com/kirill_bykov?ref=kirill-bykov.com"
#scholar:	    "https://scholar.google.com/citations?user=tI39EK8AAAAJ&hl=en"
#linkedin:	  "https://www.linkedin.com/in/bykovkirill/"
#substack:	  "https://www.prometheanirreverence.com"
#email:	  "kirill.bykov@tum.de"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#   path:	     rss-feed.xml
