# Site Settings

paginate:            5

highlighter:         rouge


title: Kirill Bykov
description: Personal GitHub blog
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
plugins:             [jekyll-paginate-v2, jekyll-sitemap, jekyll-feed]

gems:
  - jekyll-feed
  - jekyll-paginate

# Customise feed settings (uncommenting following two fields to customise feed title and description)
#title:		     "Lagrange-Custom"
#description:	     "a minimalist Jekyll theme-Custom"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#   path:	     rss-feed.xml
